language: java
sudo: false

before_script:
  - 'export MAVEN_OPTS="-Djava.util.logging.config.file=logging.properties"'

script: mvn compile assembly:single && mvn clean test

jdk:
  - oraclejdk8

notifications:
  slack: bigg:8Wgsmh1VKQU3A3mMISttZKoW

branches:
  only:
    - master
